NHSD.BuyingCatalogue.Ordering.Api.sln, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests.csproj
6101 added unit and integration test projects
=> 6101: added test projects

README.md
Initial read me file to be updated as the service is developed
=> 6101: added template README.md 

azure-pipelines.yml
[AB#5542](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5542)
- use latest .NET Core SDK
- update job display name to describe what they are doing more accurately
- stop building dev every time
=> Fix Specflow build error

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Summary/OrderSummaryModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Summary/SectionModel.cs
[AB#6737](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6737)
=> Get order summary canned data endpoint

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderDescriptionModel.cs
[AB#6889](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6889)
=> 5322: GET & PUT canned data - description

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Application/Persistence/IOrderRepository.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Repositories/OrderRepository.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Description 5322.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderDescriptionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Utils/IntegrationTestDatabase.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs
[AB#6892](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6892)
=> 5322: GET - order description

src/NHSD.BuyingCatalogue.Ordering.Api/Dockerfile, src/NHSD.BuyingCatalogue.Ordering.Api/appsettings.json
[AB#4826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4826)
=> 4826: Add projects to dockerfile

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Summary/OrderSummaryModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary 5321.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSummarySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs
[AB#6736](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6736)
=> 5321: Get order summary

azure-pipelines.yml
[AB#7041](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7041)
=> Enable pushing to prod acr

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary 5321.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs
Story: [AB#5161](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5161)
Task: [AB#7040](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7040)
=> 5161: Fix order description section id

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql
[AB#7049](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7049)
=> 5322: OrderName db

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Description 5322.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderDescriptionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Entities/OrderEntity.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/SqlRunner.cs
Story: [AB#5322](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5322)
Task: [AB#7050](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7050)
=> 5322: PUT - name of the user

src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs
Story: [AB#6729](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6729)
Task: [AB#6943](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6943)
=> 6943: Additional logging on config

src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs
Story: [AB#7103](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7103)
Task [AB#7107](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7107)
=> 7107: PII flag set true in dev

src/NHSD.BuyingCatalogue.Ordering.Domain/Contact.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Deployment/CreateTables.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.sqlproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Contact.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/SupplierContact.sql
Task: [AB#7203](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7203)
=> 4616: Order table address & organisation contact db

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Contact.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql
[AB#7205](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7205)  added supplier data columns to order table
=> 7205: Added supplier data columns to order table

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs
Task: [AB#7371](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7371)
=> 4616: Empty result bug

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Common/CommonSteps.cs
Task: [AB#7371](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7371)
=> 4616: Integration test empty get

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderingPartyModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrganisationModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Party.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/AddressSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Common/CommonSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Common/Response.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderingPartySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs
Task: [AB#7392](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7392)
=> 4616: JSON contract change

src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/AddressExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ContactExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/PrimaryContactModel.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Contact.sql, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SupplierSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/AddressExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/ContactExtensionsTests.cs
Story: [AB#4621](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4621)
Task: [AB#7385](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7385)
=> 4621: Put supplier validation

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderStatus.sql
Story: [AB#7103](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7103)
Task: [AB#7254](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7254)
=> 7254: Primary key set on db tables

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SupplierSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/AddressExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ContactExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/ContactBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/AddressExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/ContactExtensionsTests.cs
Task: [AB#7427](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7427)
=> Feature/4616 Fix the insert of a new contact

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SupplierSectionController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update .feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/AccessTokenSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/AddressSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/ContactSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderingPartySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/SupplierSectionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Support/ScenarioContextKeys.cs
Story: [AB#7103](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7103)
Task: [AB#7414](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7414)
=> 7414: Authorize policies fix

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/ServiceRecipientsModel.cs
Story: [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task: [AB#7469](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7469), [AB#7470](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7470)
=> 7412: Service Recipients Canned Data

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CatalogueSolutionModel.cs
Story: [AB#4631](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4631)
Task: [AB#7476](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7476)
=> 7476: Added Canned Data for GET and PUT

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/ServiceRecipientModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/ServiceRecipientsModel.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Deployment/CreateTables.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.sqlproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/ServiceRecipient.sql
Story: [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task: [AB#7489](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7489)
=> 7412: Add service recipients table (& amend canned data)

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql
Story [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task [AB#7479](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7479)
=> 7288: Added Column ServiceRecipientsViewed

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql
Story [AB#4631](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4631)
Task [AB#7478](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7478)
=> 7478: Added Column CatalogueSolutionsViewed

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CatalogueSolutionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CatalogueSolutionsControllerTest.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Entities/OrderEntity.cs
Story: [AB#4631](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4631)
Task: [AB#7481](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7481)
=> 7481: Implemented PUT for Catalogue Solutions

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs
Story: [AB#7230](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7230)
Task: [AB#7689](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7689)
=> 7230: Reset Catalogue Solutions viewed flag

charts/ordapi-db-deploy/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7663](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7663)
=> Change job's name to allow re-deployments

charts/ordapi-db-deploy/templates/_helpers.tpl, charts/ordapi/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7440](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7440)
=> Use local repository even when useLocalImage=false

GitVersion.yml
[AB#7824](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7824)
=> add mainline versioning file

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderItemModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderListItemModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs
Story: [AB#5127](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5127)
Task: [AB#7870](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7870)
=> 7870: Add canned data for Get Order endpoint

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment/Dockerfile, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Hooks/IntegrationHook.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/DatabaseHealthCheck.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/HttpClientAwaiter.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/OrderingApiHealthCheck.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Utils/Settings.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/appsettings.json
Story: [AB#7827](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7827)
Task: [AB#7982](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7982)
=> 7982: Check db is running on integration tests

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Deployment/InsertProvisioningTypes.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderItem.sql
Story: [AB#7840](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7840)
Task: [AB#8046](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8046)
=> 7840: Order item db change

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetOrderItem.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetOrderItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetCatalogueSolutionOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CatalogueSolutionsControllerTests.cs
Story: [AB#7840](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7840) 
Task: [AB#7854](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7854)
=> 7840: Get catalogue order item

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs
Story: [AB#8122](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8122)
=> 8122: Canned Data Fix

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/CataloguePriceUnit.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderItem.sql, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/OrderItemEntityTypeConfiguration.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateCatalogueSolutionOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CatalogueSolutionsControllerTests.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Entities/OrderItemEntity.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/EntityBuilder/OrderItemEntityBuilder.cs
Story: [AB#8119](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8119)
Task: [AB#8202](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8202)
=> 8119: Price name change

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetCatalogueSolutionOrderItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetCatalogueSolutionOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CatalogueSolutionsControllerTests.cs
Story: [AB#8119](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8119)
Task: [AB#8249](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8249)
=> 8119: Service Recipient Name Fix

azure-pipelines.yml, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment/Dockerfile, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/appsettings.json
Story: [AB#8099](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8099)
Task: [AB#8093](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8093)
=> Increase HC timeout

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/TimeUnit.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetOrderRequestSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Support/NullStringValueRetriever.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderItemTests.cs
Story: [AB#8124](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8124)
Task: [AB#8130](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8130)
=> 8130: Added calculation for total cost per year

src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/CreateOrderItemRequestExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CreateOrderItemSolutionModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/TimeUnitModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Builders/CreateCatalogueSolutionOrderItemRequestPayloadBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Create Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateCatalogueSolutionOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/Payloads/CreateCatalogueSolutionOrderItemRequestPayload.cs
Story: [AB#7405](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7405)
Task: [AB#8233](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8233)
=> 8233: Updated TimeUnit to be an object in CreateOrderItem

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderItemBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Data/TimeUnitEnum.cs
Story: [AB#8124](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8124)
Task: [AB#8267](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8267)
=> 8124: Time unit & estimation period implement

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/CreateOrderItemService.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/OrderItemEntityTypeConfiguration.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/OrderItems Get All.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderItemsResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderItemBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/Builders/OrderItemBuilder.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/EntityBuilder/OrderItemEntityBuilder.cs
Story: [AB#7263](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7263)
Task: [AB#8322](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8322)
=> 7263: Sort by created time

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs
Story: [AB#8124](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8124)
Task: [AB#8350](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8350)
=> 8124: Missing delivery date

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/CreateOrderItemService.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/ProvisioningType.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Create.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateCatalogueSolutionOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CreateCatalogueSolutionOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderItemServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/ProvisioningTypeTests.cs
Story: [AB#7730](https://buyingcatalog.visualstudio.com/Buying%20Catalogue/_workitems/edit/7730)
Task: [AB#7730](https://buyingcatalog.visualstudio.com/Buying%20Catalogue/_workitems/edit/8351)
=> Feature/7730 Fix estimation period

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CatalogueSolutionsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/TimeUnitExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetCatalogueSolutionOrderItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetCatalogueSolutionOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderItemBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CatalogueSolutionsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/TimeUnitExtensionsTests.cs
Story: [AB#7405](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7405)
Task: [AB#8382](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8382)
=> Feature/7405 Add time unit to get catalogue solution endpoint

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/ServiceRecipientSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/ServiceRecipientBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs
Story: [AB#8203](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8203)
Task: [AB#8317](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8317)
=> 8203: Service recipients - alphabetical order

src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Catalogue Solutions Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/OrderItem Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateCatalogueSolutionOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/UpdateCatalogueSolutionOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/UpdateOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderItemTests.cs
Bug: [AB#8514](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8514)
Task: [AB#8519](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8519)
=> 8519: Updated OrderItem to only update estimation period for OnDemand

src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetOrderItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/OrderItems Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderItemResponseBase.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs
Story: [AB#7580](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7580)
Task: [AB#8498](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8498)
=> 8498: Added estimation period to get item

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/SectionModelListBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderBuilder.cs
Story: [AB#5115](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5115)
Task: [AB#8529](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8529)
=> 5115: Update GET order summary to include associated

src/NHSD.BuyingCatalogue.Ordering.Persistence/Repositories/OrderRepository.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders CreateOrder.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/SectionStatusUpdateSteps.cs
Story: [AB#7829](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7829)
Task: [AB#8472](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8472)
=> 8472: Update initial order ID to start from 10000

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/CostType.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetOrderRequestSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderItemTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Story: [AB#7702](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7702)
Task: [AB#8468](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8468)
=> 7702: Year and monthly order cost

src/NHSD.BuyingCatalogue.Ordering.Api/Attributes/CreateOrderItemBaseModelConverter.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CreateOrderItemAdditionalServiceModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CreateOrderItemAssociatedServiceModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CreateOrderItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Builders/CreateOrderItemRequestPayloadBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Create Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Create.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateAssociatedServiceOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateOrderItemBaseRequest.cs
Story [AB#4832](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4832)
Task [AB#8446](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8446)
=> 4832: Added support for the creation of Asssocated Service order items.

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderItem.sql
Story: [AB#7048](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7048)
Task: [AB#8455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8455)
=> 7048: Database change - orderItem

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Items Get All.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/EntityBuilder/OrderEntityBuilder.cs
Story: [AB#7048](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7048)
Task: [AB#8455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8455)
=> 7048: Associated service bug fix

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs
Story: [AB#4832](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4832)
Task: [AB#8718](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8718)
=> 4832: Edit price bug

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/SectionModelListBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderBuilder.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Entities/OrderEntity.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/EntityBuilder/OrderEntityBuilder.cs
Story: [AB#5436](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5436)
Task: [AB#8655](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8655)
=> 5436: Funding source summary

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/FundingSourceController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/UpdateFundingSourceModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Funding Source Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/Payloads/UpdateFundingSourceRequestPayload.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateFundingSourceRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/FundingSourceSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/FundingSourceControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/FundingSourceControllerTests.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Entities/OrderEntity.cs
Story: [AB#5437](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5437)
Task: [AB#8668](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8668)
=> Feature 5437 funding source put

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Story: [AB#7693](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7693)
Task: [AB#8686](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8686)
=> 8686: Added One Off Cost to Order GET

src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, src/NHSD.BuyingCatalogue.Ordering.Common/NHSD.BuyingCatalogue.Ordering.Common.csproj, src/NHSD.BuyingCatalogue.Ordering.Persistence/NHSD.BuyingCatalogue.Ordering.Persistence.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests.csproj
Story: [AB#8492](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8492)
Task: [AB#8785](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8785)
=> 8492: Nuget package updates

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Story: [AB#7703](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7703)
Task: [AB#8819](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8819)
=> 7703: Populate total cost of ownership

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql
Story [AB#5287](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5287)
Task [AB#8853](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8853)
=> 5287 add IsDeleted column to order table

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql
Story [AB#6859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6859)
Task [AB#9071](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9071)
=> 6859: Added date Completed column to order.

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderListItemModel.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/Entities/OrderEntity.cs, tests/NHSD.BuyingCatalouge.Ordering.Api.Testing.Data/EntityBuilder/OrderEntityBuilder.cs
Story: [AB#6859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6859)
Task: [AB#9072](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9072)
=> Add date completed to GET orders

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderListItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs
Story: [AB#8741](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8741)
Task: [AB#9079](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9079)
=> 8741: Add funding source to list orders

src/NHSD.BuyingCatalogue.Ordering.Persistence/Repositories/OrderRepository.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders CreateOrder.feature
Story: [AB#5287](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5287)
Task: [AB#9220](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9220)
=> Feature/9220 Fix create new order after delete

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Errors/ErrorMessages.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/ErrorDetails.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Orders/OrderErrors.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/OrderEntityTypeConfiguration.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderStatusSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Story: [AB#6859](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6859)
Task: [AB#9073](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9073)
=> Feature/6859 Set the completed date when an order status is set to complete

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderModel.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderBuilder.cs
Story: [AB#8904](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8904)
Task: [AB#9346](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9346)
=> 8904: Add date completed

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CompleteOrder/CompleteOrderService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/EmailSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CompleteOrderServiceTests.cs
Story: [AB#3928](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/3928)
Task: [AB#9640](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9640)
=> 3928: Funding source email bug

src/NHSD.BuyingCatalogue.Ordering.Api/appsettings.json, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature
Story: [AB#9586](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9586)
Task: [AB#9649](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9649)
=> 9586: Email conf changes

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreatePurchasingDocument/CreatePurchasingDocumentService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature
Story: [AB#9283](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9283)
Task: [AB#9642](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9642)
=> 9283: Fix service recipient issue

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CompleteOrder/CompleteOrderService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderStatusSteps.cs
Story: [AB#9283](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9283)
Task: [AB#9745](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9745)
=> 9283: File name fix

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreatePurchasingDocument/CreatePurchasingDocumentService.cs
Story: [AB#9283](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9283)
Task: [AB#9746](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9746)
=> 9283: Service recipient dictionary bug

azure-pipelines.yml
Task: [AB#9842](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9842)  
Story: [AB#6869](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6869)
=> Workaround for Helm Version issues

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/DefaultDeliveryDateController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/DefaultDeliveryDateModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Settings/ValidationSettings.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/DefaultDeliveryDateValidator.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/IDefaultDeliveryDateValidator.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.sqlproj, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Default Delivery Date Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/DefaultDeliveryDateEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/DefaultDeliveryDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Validation/DefaultDeliveryDateValidatorTests.cs
Story: [AB#8952](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8952)
Task: [AB#9905](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9905)
=> Add default delivery date validation

azure-pipelines.yml
Also reinstates latest version of helm following fix for ACR issue.
Activity: [AB#9971](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9971)
Task: [AB#10040](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10040)
=> Remove development branch from pipeline

azure-pipelines.yml, src/NHSD.BuyingCatalogue.Ordering.Api/Dockerfile, src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj
Activity: [AB#10199](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10199)
Task: [AB#10251](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10251)
=> Fix docker build

src/NHSD.BuyingCatalogue.Ordering.Api/Models/ServiceRecipientModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/ServiceRecipientValidator.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Validation/ServiceRecipientModelValidatorTests.cs
Story: [AB#10328](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10328)
Task: [AB#10341](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10341)
=> Make service recipient model validation fluent

src/NHSD.BuyingCatalogue.Ordering.Api/Models/ItemUnitModel.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderItem.sql, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Create Validation Bulk.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Create Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateAdditionalServiceOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateAssociatedServiceOrderItemRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateCatalogueSolutionOrderItemRequest.cs
Activity: [AB#10640](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10640)
Task: [AB#10641](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10641)
=> Increase max length of item unit description to 40

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetOrderItemModel.cs, src/NHSD.BuyingCatalogue.Ordering.Application/Persistence/IOrderQuery.cs, src/NHSD.BuyingCatalogue.Ordering.Application/Persistence/IOrderRepository.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/ServiceInstanceItem.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment.csproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Functions/GetServiceInstanceIncrement.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Functions/HasParentSolution.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Indexes/IX_ServiceInstance.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.sqlproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderItem.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Views/ServiceInstanceItem.sql, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/ApplicationDbContext.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/ServiceInstanceItemEntityTypeConfiguration.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Repositories/OrderQuery.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Repositories/OrderRepository.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Service Instance ID.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/CreateOrderItemBaseRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderItemsResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/OrderItemEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/OrderItemEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/ControllerBaseCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs
Stories: [AB#10039](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10039), [AB#10511](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10511)
Task: [AB#10873](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10873)
=> Add service instance ID to GET order items endpoint

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderItemModel.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetOrderRequestSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderBuilder.cs
Story: [AB#11035](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11035)
Task: [AB#11088](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11088)
=> Add service instance ID to GET order endpoint

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ClaimsPrincipalExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/TimeUnitExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Errors/ErrorMessages.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Summary/SectionModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/OrderItemValidator.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/IdentityService.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/UpdateOrderItem/UpdateOrderItemRequest.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/AggregateValidationResult.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/DefaultDeliveryDateValidator.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Orders/OrderErrors.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Results/Result.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Builders/OrderSummaryDataBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Support/GenerateStringLengthValueRetriever.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/ServiceRecipientReferenceList.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/AddressEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/ContactEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/OrderEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/OrderItemEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderItemsControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrdersControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/SectionModelListBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/SectionStatusControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/Services/CreatePurchasingDocumentServiceBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderItemServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreatePurchasingDocumentServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderItemBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/ValueObjectTests.cs
=> Use targeted type new expression

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SectionStatusController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/DeleteOrderRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/Payloads/UpdateFundingSourceRequestPayload.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CreateOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CreateOrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Support/ScenarioContextExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderServiceTests.cs
=> Tidy using statements

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Attributes/CommencementDateAttribute.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/SwaggerExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreatePurchasingDocument/CsvStreamStreamWriter.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/CataloguePriceUnit.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderDescription.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderOrganisationId.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Results/Result.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderingPartySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Support/GenerateStringLengthValueRetriever.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/OrderingApiHealthCheck.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/AddressEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/ContactEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/OrderEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/ServiceRecipientEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/OrderItemEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
=> Fix violations of StyleCop rules SA1119–SA1137

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/CreateOrderItemService.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/GetOrderItemsRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderItemsResponse.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CommencementDateSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/UpdateOrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/AddressEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/ContactEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/OrderEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/OrderItemEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/ServiceRecipientEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CommencementDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/FundingSourceControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SectionStatusControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SupplierSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CompleteOrderServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CsvStreamWriterTests.cs
=> Fix parameter style violations

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Logging/SerilogRequestLoggingOptions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/FluentValidationOptions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateFundingSourceRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateOrderStatusRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/ServiceRecipientsModelBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SupplierSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderItemServiceTests.cs
=> Fix naming violations (excluding prefixes)

tests/.editorconfig, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs
=> Fix tuple naming in tests

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CommencementDateController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/FundingSourceController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SectionStatusController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SupplierSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrder/CreateOrderService.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/NHSD.BuyingCatalogue.Ordering.Domain.csproj, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Results/Result.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/OrderEntityTypeConfiguration.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/OrderItemEntityTypeConfiguration.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/PropertyBuilderExtensions.cs, tests/.editorconfig, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/Field.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderItemBuilder.cs
=> Fix field names in non-test projects

tests/.editorconfig, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/ContactBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/CreateOrderRequestBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/FundingSourceControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderSummaryModelBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrdersControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/SectionModelListBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/SectionStatusControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/ServiceRecipientBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/ServiceRecipientModelBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/Services/CompleteOrderServiceBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/Services/UpdateOrderItemServiceBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/UpdateOrderItemModelBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/AddressBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/ValueObjectTests.cs
=> Fix naming in unit test projects

.editorconfig, src/NHSD.BuyingCatalogue.Ordering.Api/Models/AddressModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/GetServiceRecipientModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderingPartyModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/Summary/SectionModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/SupplierModel.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Address.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Contact.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Organisation.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Builders/OrderSummaryData.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateFundingSourceRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateOrderStatusRequest.cs
=> Fix element spacing

.editorconfig, .gitattributes, NHSD.BuyingCatalogue.Ordering.Api.sln, src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, src/NHSD.BuyingCatalogue.Ordering.Application/NHSD.BuyingCatalogue.Ordering.Application.csproj, src/NHSD.BuyingCatalogue.Ordering.Common/NHSD.BuyingCatalogue.Ordering.Common.csproj, src/NHSD.BuyingCatalogue.Ordering.Domain/NHSD.BuyingCatalogue.Ordering.Domain.csproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment.csproj, src/NHSD.BuyingCatalogue.Ordering.Persistence/NHSD.BuyingCatalogue.Ordering.Persistence.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CommencementDateSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests.csproj
Activities: [AB#9815](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9815), [AB#11100](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11100)
Tasks: [AB#9817](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9817), [AB#11104](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11104)
=> Fix remaining StyleCop violations

.gitattributes, tests/.editorconfig, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Hooks/IntegrationHook.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Responses/GetOrderItemResponseBase.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CommencementDateSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/EmailSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/GetOrderRequestSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/HealthChecksSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderDescriptionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderStatusSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSummarySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/SectionStatusUpdateSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/ServiceRecipientSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/SupplierSectionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/HttpClientAwaiter.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/OrderingApiHealthCheck.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/AddressExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/ContactExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/SwaggerExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Models/SectionModelTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderItemServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreatePurchasingDocumentServiceTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/OrderItemValidatorTests.cs
Task: [AB#11093](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11093)
=> Fix most test project FxCop violations

.editorconfig, NHSD.BuyingCatalogue.Ordering.Api.sln, NHSD.BuyingCatalogue.Ordering.Api.sln.DotSettings, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/.editorconfig, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CommencementDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/FundingSourceControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SupplierSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Requests/CompleteOrderRequestTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/SerilogRequestLoggingOptionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CreateOrderItemRequestTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CsvStreamWriterTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderDescriptionTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderStatusTests.cs
Task: [AB#11093](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11093)
=> Fix remaining FxCop violations

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Funding Source Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Funding Source Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Commencement Date.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Create Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Create.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Items Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Commencement Date.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Healthcheck.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders CreateOrder.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Section Status Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update.feature
=> Clean up feature files

NHSD.BuyingCatalogue.Ordering.Api.sln.DotSettings, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CreateOrderModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/ErrorResponseModel.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Repositories/DefaultDeliveryDateRepository.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateFundingSourceRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Requests/UpdateOrderStatusRequest.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/FundingSourceSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/ControllerBaseCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/EnumValueByNameCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/ValueObjectTests.cs
=> Seal unsealed class

src/NHSD.BuyingCatalogue.Ordering.Api/Properties/launchSettings.json, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CreateOrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSummarySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderingPartySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/SupplierSectionSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/Support/OrderSummaryDataFactory.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Utils/IntegrationDatabase.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/EnumValueByNameCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/HttpContextAccessorCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/OrderingCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/SingleServiceRecipientOrderCustomization.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Builders/OrderSummaryModelBuilder.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderItemTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Activity: [AB#11263](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11263)
=> Fix a number of R# warning

NHSD.BuyingCatalogue.Ordering.Api.sln.DotSettings, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/JwtBearerOptionsExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/SwaggerExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Default Delivery Date Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Funding Source Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Hooks/IntegrationHook.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/AccessTokenSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSummarySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/AwaitHttpClient.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Support/OrderingApiHealthCheck.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Validation/ValidationResultTests.cs
Activity: [AB#11263](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11263)
=> Fix spelling issues

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CommencementDateController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/FundingSourceController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SupplierSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ClaimsPrincipalExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/ServiceRecipientModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/IdentityService.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/DefaultDeliveryDate.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/OrderItem.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/ServiceRecipient.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/TimeUnitExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/AddressSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/ContactSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CreateOrderItemBulkSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSummarySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/ServiceRecipientSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/DefaultDeliveryDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/ClaimsPrincipalExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/OrderItemValidatorTests.cs
Activity: [AB#11263](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11263)
=> Address R# warnings

.editorconfig, NHSD.BuyingCatalogue.Ordering.Api.sln.DotSettings
Task: [AB#9815](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9815)
Activity: [AB#11110](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11110)
=> Ensure consistent code style settings

src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/OrderEntity.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/EntityBuilder/OrderEntityBuilder.cs
Activity: [AB#9714](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9714)
Task: [AB#7941](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7941)
=> Remove organisation billing address ID

src/NHSD.BuyingCatalogue.Ordering.Api/Authorization/OrderLookupOrganisationAuthorizationFilter.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Authorization/OrderLookupOrganisationAuthorizationFilterTests.cs
Task: [AB#11053](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11053)
=> Update authorization filter

src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/AddressExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ClaimsPrincipalExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ContactExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderItemRecipientExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/AddressExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/ContactExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderItemRecipientExtensionsTests.cs
Task: [AB#11053](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11053)
=> Update extension methods and corresponding tests

src/NHSD.BuyingCatalogue.Ordering.Api/ModelBinding/OrderModelBinder.cs, src/NHSD.BuyingCatalogue.Ordering.Api/ModelBinding/OrderModelBinderProvider.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/ModelBinding/OrderModelBinderTests.cs
Task: [AB#11053](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11053)
=> Improve model binding

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/CommencementDateController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/DefaultDeliveryDateController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/FundingSourceController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderingPartyController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SectionStatusController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SupplierSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CommencementDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/DefaultDeliveryDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/FundingSourceControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SectionStatusControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SupplierSectionControllerTests.cs
[AB#11053](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11053)
=> Update controllers and tests

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/OrderItemValidator.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Validation/AggregateValidationResult.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/ErrorDetails.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/ErrorDetailsTests.cs
Activity: [AB#12939](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12939)
Task: [AB#11053](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11053)
=> Add parent name to error details

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/SectionStatusController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/CreateOrderModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/NHSD.BuyingCatalogue.Ordering.Api.csproj, src/NHSD.BuyingCatalogue.Ordering.Persistence/NHSD.BuyingCatalogue.Ordering.Persistence.csproj, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SectionStatusControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests.csproj
Activity: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
=> Fix issues refactor issues

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderItemModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Models/OrderModel.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/OrderItemValidator.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/ServiceInstanceItem.cs, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Functions/GetServiceInstanceIncrement.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Functions/HasParentSolution.sql, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.sqlproj, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Views/ServiceInstanceItem.sql, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/ServiceInstanceItemEntityTypeConfiguration.cs, tests/NHSD.BuyingCatalogue.Ordering.Common.UnitTests/Builders/OrderBuilder.cs
Activity: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
=> Fix refactor bugs

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/OrderItemRecipientExtensions.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, src/NHSD.BuyingCatalogue.Ordering.Persistence/Data/OrderEntityTypeConfiguration.cs
Activity: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
=> Fix order completion and recipient ordering issues

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Update.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update Validation.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Supplier Section Update.feature
=> Update ordering party and supplier feature files

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Calculations.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Commencement Date.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary Section Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary.feature
=> Update order GET and summary feature files

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Commencement Date.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature
=> Update order delete and update feature files

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Healthcheck.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders CreateOrder.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Section Status Update.feature
=> Update orders and section status feature files

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Service Instance ID.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients Put.feature
[AB#13002](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13002)
=> Update service instance and service recipients feature files

azure-pipelines.yml
=> Reinstate integration tests in pipeline

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/ServiceRecipientsSectionController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/ServiceRecipients GetAll.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs
Story: [AB#12946](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12946)
Task: [AB#13158](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13158)
=> Fix missing recipients for additional services

tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Authorization/OrderLookupOrganisationAuthorizationFilterTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/InMemoryDbAutoDataAttribute.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/AutoFixture/InMemoryDbInlineAutoDataAttribute.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/CommencementDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/DefaultDeliveryDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/FundingSourceControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderingPartyControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SectionStatusControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/ServiceRecipientsSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/SupplierSectionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/ModelBinding/OrderModelBinderTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Services/CompleteOrderServiceTests.cs
Activity: [AB#13236](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13236)
Task: [AB#13237](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13237)
=> Make in-memory DB unit tests more robust

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/PricingUnit.sql
Story [AB#13140](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13140)
Task [AB#13226](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13226)
=> Increase length of Description column in PricingUnit tables to 100

src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/OrderItemRecipients.sql
Bug: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
Task: [AB#13274](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13274)
=> Fix save additional service

tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/.editorconfig, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Commencement Date.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CommencementDateSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemDeleteSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemRecipientsSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Utils/IntegrationDatabase.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.Testing.Data/Entities/OrderItemEntity.cs
Story: [AB#9038](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9038)
Task: [AB#13017](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13017)
Also re-enabled some ignored tests.
=> Delete order item integration tests

src/NHSD.BuyingCatalogue.Ordering.Api/Services/CreateOrderItem/CreateOrderItemService.cs
Bug: [AB#13000](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13000)
Task: [AB#13362](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13362)
=> Fix save associated service

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderDescriptionController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, src/NHSD.BuyingCatalogue.Ordering.Contracts/IOrderDescriptionService.cs, src/NHSD.BuyingCatalogue.Ordering.Services/OrderDescriptionService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderDescriptionControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Services.UnitTests/OrderDescriptionServiceTests.cs
Story [AB#13236](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13236)
Task [AB#13414](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13414)
=> Move DB functionality to service layer – OrderDescriptionController

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Set AdditionalServicesViewed to false if all Catalogue Solutions deleted
Story: [AB#9040](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9040)
Task: [AB#13713](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13713)
=> ALL Catalogue Solutions deleted

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/DefaultDeliveryDateController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Startup.cs, src/NHSD.BuyingCatalogue.Ordering.Contracts/IDefaultDeliveryDateService.cs, src/NHSD.BuyingCatalogue.Ordering.Services/DefaultDeliveryDateService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Default Delivery Date Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/DefaultDeliveryDateSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/DefaultDeliveryDateControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Services.UnitTests/DefaultDeliveryDateServiceTests.cs
Story [AB#13236](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13236)
Task [AB#13570](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13570)
=> Move DB functionality to service layer – DefaultDeliveryDateController

src/NHSD.BuyingCatalogue.Ordering.Domain/Order.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderItemDeleteSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Story [AB#13906](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13906)
Task [AB#14018](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14018)
=> funding source status bug fix

src/NHSD.BuyingCatalogue.Ordering.Api/Authorization/OrderLookupOrganisationAuthorizationFilter.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Authorization/OrganisationAuthorizationFilter.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Authorization/OrganisationIdOrganisationAuthorizationFilter.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Funding Source Put.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Commencement Date.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Description.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Ordering Party Get.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/OrderingPartySteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Authorization/OrganisationAuthorizationFilterTests.cs
Activity: [AB#13236](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13236)
Task: [AB#14181](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14181)
=> Fix authorization issues and re-enable integration tests

src/NHSD.BuyingCatalogue.Ordering.Api/Authorization/OrganisationAuthorizationFilter.cs, src/NHSD.BuyingCatalogue.Ordering.Common/Constants/UserClaimTypes.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Authorization/OrderLookupOrganisationAuthorizationFilterTests.cs
Story: [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Task: [AB#13895](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13895)
=> Update User Authorization to include RelatedOrganisationId's in check

src/NHSD.BuyingCatalogue.Ordering.Api/Authorization/OrganisationAuthorizationFilter.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrdersController.cs, src/NHSD.BuyingCatalogue.Ordering.Api/Extensions/ClaimsPrincipalExtensions.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrdersControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/ClaimsPrincipalExtensionsTests.cs
Include secondary organizations in authorization check
Story: [AB#12959](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12959)
Task: [AB#13899](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13899)
=> Update create order endpoint

tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Services.UnitTests/OrderItemServiceTests.cs
Story [AB#13236](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13236)
Task [AB#13840](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13840)
=> Order item refactor based on PR comment

azure-pipelines.yml
Activity: [AB#14225](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14225)
Task: [AB#13691](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13691)
=> Do not build image on PR

NHSD.BuyingCatalogue.Ordering.Api.sln.DotSettings, azure-pipelines.yml, src/NHSD.BuyingCatalogue.Ordering.OrderingDatabase/Tables/Order.sql, src/NHSD.BuyingCatalogue.Ordering.Services/OrderService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Item Delete.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Summary Section Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Order Update Status.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Features/Orders CreateOrder.feature, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Hooks/IntegrationHook.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Steps/CreateOrderSteps.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.IntegrationTests/Utils/IntegrationDatabase.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Extensions/OrderExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Domain.UnitTests/OrderTests.cs
Activity: [AB#13236](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13236)
Task: [AB#14802](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14802)
=> Re-enable disabled unit and integration tests

src/NHSD.BuyingCatalogue.Ordering.Api/Controllers/OrderItemsController.cs, src/NHSD.BuyingCatalogue.Ordering.Contracts/IOrderItemService.cs, src/NHSD.BuyingCatalogue.Ordering.Services/OrderItemService.cs, tests/NHSD.BuyingCatalogue.Ordering.Api.UnitTests/Controllers/OrderItemsControllerTests.cs, tests/NHSD.BuyingCatalogue.Ordering.Services.UnitTests/OrderItemServiceTests.cs
Additional Services section set to incomplete
Story: [AB#14614](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14614)
Task: [AB#14906](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14906)
=> BUG - All Associated services deleted
